import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Bricolage_Grotesque } from "next/font/google";
import '@radix-ui/themes/styles.css';
import './globals.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const bricolage_grotesque_init = Bricolage_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bricolage-grotesque",
});

export const metadata: Metadata = {
  title: "Fardeen Mansoori",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricolage_grotesque_init.variable}>
        <Theme appearance='dark' >
          <Navbar />
          {children}
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
